### ISSUE TITLE
提供Taro插件？

### ISSUE THREAD

**Issue by mefengl** [dcasia/mini-program-tailwind-webpack-plugin#5]
https://github.com/pcdotfan/taro-plugin-tailwind
上面就是Taro中目前tailwind实现，但不支持反斜杠等语法。

**Comment by ItsRyanWu** [comment]
好的，我研究下

Updates: WIP #6

**Comment by ItsRyanWu** [comment]
Taro 插件已完成开发，已支持 Tailwind/Windi CSS JIT 功能，具体使用步骤请参考文档：[基于 Taro 小程序](https://www.craft.do/s/Wx2f9cjGwyZYOx/b/7C55634E-E6CA-4669-9419-194C6263E8A5/%F0%9F%91%BD_Taro_%E5%B0%8F%E7%A8%8B%E5%BA%8F)
如遇 bug 可以继续在本条 issue 反馈

**Comment by transtone** [comment]
> Taro 插件已完成开发，已支持 Tailwind/Windi CSS JIT 功能，具体使用步骤请参考文档：[基于 Taro 小程序](https://www.craft.do/s/Wx2f9cjGwyZYOx/b/7C55634E-E6CA-4669-9419-194C6263E8A5/%F0%9F%91%BD_Taro_%E5%B0%8F%E7%A8%8B%E5%BA%8F) 如遇 bug 可以继续在本条 issue 反馈

在 dev:h5 模式下不生效。class已经转换成功了，但 virtual:windi.css 文件却没有转。
`class="w-1/2 bg-[red]"`   =>  `class="hydrated w-1-s-2 bg--red-"`  

`virtual:windi.css` 的内容：
```css
.w-1\/2 {
  width: 50%;
}
.bg-\[red\] {
  --tw-bg-opacity: 1;
  background-color: rgba(255, 0, 0, var(--tw-bg-opacity));
}
```
