### ISSUE TITLE
编译 *= 语法，导致小程序编译报错

### ISSUE THREAD

**Issue by bluescurry** [dcasia/mini-program-tailwind-webpack-plugin#55]
css 代码是这样的
```css
[class*=taroify-] {
  -webkit-tap-highlight-color: transparent;
}
```
编译出来的css是这样的
```
[classcover-image, cover-view, movable-area, movable-view, scroll-view, swiper, swiper-item, view, icon, progree, rich-text, text, button, checkbox, checkbox-group, editor, form, input, label, picker, picker-view, picker-view-column, radio, radio-group, slider, switch, textarea, navigator, audio, camera, image, live-player, live-pusher, video, map, canvas=taroify-] {
  -webkit-tap-highlight-color: transparent;
}
```

在小程序上编译报错了```unexpected token `,```。麻烦看下这个问题要怎么解决
